language: python
python:
  - "2.7"
  - "3.6"

matrix:
  allow_failures:
    - python: "3.6"

#command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

#command to run tests
script: 
python -m unittest discover -s tests

after_success:
coveralls
